import os
import sys
import json
from fastapi.testclient import TestClient

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from app.main import app

client = TestClient(app)

STRATEGIC_QUESTIONS = [
    "Why do users struggle to discover new music?",
    "What are the most common frustrations with recommendations?",
    "What listening behaviors are users trying to achieve?",
    "What causes users to repeatedly listen to the same content?",
    "Which user segments experience different discovery challenges?",
    "What unmet needs emerge consistently across reviews?"
]

def generate_report():
    output_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "docs", "strategic_questions_outputs.md"))
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Voice of Customer: Strategic Analysis Outputs\n\n")
        f.write("This document presents the actual data-grounded answers generated by the Voice of Customer chatbot for the six key strategic questions.\n\n")
        
        for q in STRATEGIC_QUESTIONS:
            f.write(f"## Question: {q}\n\n")
            
            payload = {"query": q}
            resp = client.post("/insights/chat", json=payload)
            if resp.status_code == 200:
                data = resp.json()
                f.write(data["answer"])
                f.write("\n\n---\n\n")
                print(f"Generated answer for: '{q}'")
            else:
                print(f"Error querying '{q}': {resp.status_code}")
                f.write(f"Error generating answer: Status code {resp.status_code}\n\n---\n\n")
                
    print(f"Report saved to: {output_path}")

if __name__ == "__main__":
    generate_report()
