"""add_producthunt_and_youtube_raw_tables

Revision ID: 0fdf742ee0bb
Revises: 7203be27018f
Create Date: 2026-06-25 19:05:31.663260

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fdf742ee0bb"
down_revision: Union[str, Sequence[str], None] = "7203be27018f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_product_hunt_posts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ph_post_id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("votes_count", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(length=256), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload", sa.Text(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ph_post_id"),
    )
    op.create_index(
        op.f("ix_raw_product_hunt_posts_slug"), "raw_product_hunt_posts", ["slug"], unique=False
    )
    op.create_table(
        "raw_youtube_videos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("search_query", sa.String(length=256), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("comment_count", sa.Integer(), nullable=True),
        sa.Column("author", sa.String(length=256), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload", sa.Text(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id"),
    )
    op.create_index(
        op.f("ix_raw_youtube_videos_search_query"),
        "raw_youtube_videos",
        ["search_query"],
        unique=False,
    )
    op.create_table(
        "raw_product_hunt_comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ph_comment_id", sa.String(length=64), nullable=False),
        sa.Column("ph_post_id", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=256), nullable=True),
        sa.Column("votes_count", sa.Integer(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload", sa.Text(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ph_post_id"],
            ["raw_product_hunt_posts.ph_post_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ph_comment_id"),
    )
    op.create_table(
        "raw_youtube_comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("comment_id", sa.String(length=64), nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("parent_comment_id", sa.String(length=64), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=256), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload", sa.Text(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["raw_youtube_videos.video_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment_id"),
    )
    op.add_column("raw_reviews", sa.Column("raw_payload", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_reviews", "raw_payload")
    # feedback_items raw_id unique index is already handled in previous migrations
    op.drop_table("raw_youtube_comments")
    op.drop_table("raw_product_hunt_comments")
    op.drop_index(op.f("ix_raw_youtube_videos_search_query"), table_name="raw_youtube_videos")
    op.drop_table("raw_youtube_videos")
    op.drop_index(op.f("ix_raw_product_hunt_posts_slug"), table_name="raw_product_hunt_posts")
    op.drop_table("raw_product_hunt_posts")
    # ### end Alembic commands ###
