"""add_analysis_run_and_feedback_item_analysis_fields

Revision ID: 27a6a2e68447
Revises: 4e498cf36b35
Create Date: 2026-06-25 20:05:58.438048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a6a2e68447'
down_revision: Union[str, Sequence[str], None] = '4e498cf36b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('skipped_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('fallback_count', sa.Integer(), nullable=False),
    sa.Column('provider_primary', sa.String(length=64), nullable=False),
    sa.Column('provider_fallback', sa.String(length=64), nullable=False),
    sa.Column('model_primary', sa.String(length=128), nullable=False),
    sa.Column('model_fallback', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('feedback_items', sa.Column('issue_category', sa.String(length=128), nullable=True))
    op.add_column('feedback_items', sa.Column('topics', sa.Text(), nullable=True))
    op.add_column('feedback_items', sa.Column('user_segment', sa.String(length=128), nullable=True))
    op.add_column('feedback_items', sa.Column('listening_intent', sa.String(length=128), nullable=True))
    op.add_column('feedback_items', sa.Column('loop_cause', sa.String(length=128), nullable=True))
    op.add_column('feedback_items', sa.Column('unmet_needs', sa.Text(), nullable=True))
    op.add_column('feedback_items', sa.Column('analysis_confidence', sa.Float(), nullable=True))
    op.add_column('feedback_items', sa.Column('analysis_version', sa.String(length=64), nullable=True))
    op.add_column('feedback_items', sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('feedback_items', sa.Column('analysis_evidence', sa.Text(), nullable=True))
    op.add_column('feedback_items', sa.Column('analysis_provider', sa.String(length=64), nullable=True))
    op.add_column('feedback_items', sa.Column('analysis_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_items', 'analysis_error')
    op.drop_column('feedback_items', 'analysis_provider')
    op.drop_column('feedback_items', 'analysis_evidence')
    op.drop_column('feedback_items', 'analyzed_at')
    op.drop_column('feedback_items', 'analysis_version')
    op.drop_column('feedback_items', 'analysis_confidence')
    op.drop_column('feedback_items', 'unmet_needs')
    op.drop_column('feedback_items', 'loop_cause')
    op.drop_column('feedback_items', 'listening_intent')
    op.drop_column('feedback_items', 'user_segment')
    op.drop_column('feedback_items', 'topics')
    op.drop_column('feedback_items', 'issue_category')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
