"""add_durable_analysis_fields

Revision ID: 6b8269d4a8b7
Revises: ac19da346d3f
Create Date: 2026-06-28 02:47:17.553681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8269d4a8b7'
down_revision: Union[str, Sequence[str], None] = 'ac19da346d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_items', sa.Column('analysis_status', sa.String(length=32), server_default='pending', nullable=False))
    op.add_column('feedback_items', sa.Column('analysis_model', sa.String(length=64), nullable=True))
    op.add_column('feedback_items', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('feedback_items', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_feedback_items_analysis_status'), 'feedback_items', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_feedback_items_analyzed_at'), 'feedback_items', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_feedback_items_issue_category'), 'feedback_items', ['issue_category'], unique=False)
    op.create_index(op.f('ix_feedback_items_sentiment'), 'feedback_items', ['sentiment'], unique=False)
    
    # Backfill already analyzed feedback items to 'complete'
    op.execute("UPDATE feedback_items SET analysis_status = 'complete' WHERE analyzed_at IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_items_sentiment'), table_name='feedback_items')
    op.drop_index(op.f('ix_feedback_items_issue_category'), table_name='feedback_items')
    op.drop_index(op.f('ix_feedback_items_analyzed_at'), table_name='feedback_items')
    op.drop_index(op.f('ix_feedback_items_analysis_status'), table_name='feedback_items')
    op.drop_column('feedback_items', 'failure_reason')
    op.drop_column('feedback_items', 'retry_count')
    op.drop_column('feedback_items', 'analysis_model')
    op.drop_column('feedback_items', 'analysis_status')
    # ### end Alembic commands ###
