"""initial schema

Revision ID: 730156d05dab
Revises:
Create Date: 2026-06-21 00:11:33.294313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "730156d05dab"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("rating_or_score", sa.Float(), nullable=True),
        sa.Column("author", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("app_version", sa.String(length=64), nullable=True),
        sa.Column("subreddit", sa.String(length=128), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("raw_table", sa.String(length=32), nullable=True),
        sa.Column("raw_id", sa.String(length=36), nullable=True),
        sa.Column("sentiment", sa.String(length=16), nullable=True),
        sa.Column(
            "normalized_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedback_items_created_at"), "feedback_items", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_feedback_items_platform"), "feedback_items", ["platform"], unique=False
    )
    op.create_index(op.f("ix_feedback_items_raw_id"), "feedback_items", ["raw_id"], unique=False)
    op.create_index(
        op.f("ix_feedback_items_source_type"), "feedback_items", ["source_type"], unique=False
    )
    op.create_table(
        "raw_reddit",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("item_type", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("author", sa.String(length=256), nullable=True),
        sa.Column("subreddit", sa.String(length=128), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("permalink", sa.String(length=1024), nullable=True),
        sa.Column("reddit_id", sa.String(length=32), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_raw_reddit_reddit_id"), "raw_reddit", ["reddit_id"], unique=False)
    op.create_table(
        "raw_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("author", sa.String(length=256), nullable=True),
        sa.Column("platform", sa.String(length=64), nullable=True),
        sa.Column("review_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("app_version", sa.String(length=64), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analysis_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("feedback_item_id", sa.String(length=36), nullable=True),
        sa.Column("result_type", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column(
            "analyzed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["feedback_item_id"],
            ["feedback_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_results_feedback_item_id"),
        "analysis_results",
        ["feedback_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_result_type"), "analysis_results", ["result_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_results_result_type"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_feedback_item_id"), table_name="analysis_results")
    op.drop_table("analysis_results")
    op.drop_table("raw_reviews")
    op.drop_index(op.f("ix_raw_reddit_reddit_id"), table_name="raw_reddit")
    op.drop_table("raw_reddit")
    op.drop_index(op.f("ix_feedback_items_source_type"), table_name="feedback_items")
    op.drop_index(op.f("ix_feedback_items_raw_id"), table_name="feedback_items")
    op.drop_index(op.f("ix_feedback_items_platform"), table_name="feedback_items")
    op.drop_index(op.f("ix_feedback_items_created_at"), table_name="feedback_items")
    op.drop_table("feedback_items")
    # ### end Alembic commands ###
